-- MySQL Script generated by MySQL Workbench
-- Wed Sep 15 20:36:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LaRockola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LaRockola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LaRockola` DEFAULT CHARACTER SET utf8 ;
USE `LaRockola` ;

-- -----------------------------------------------------
-- Table `LaRockola`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LaRockola`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LaRockola`.`Artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LaRockola`.`Artista` (
  `idArtistas` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `nacionalidad` VARCHAR(20) NULL,
  PRIMARY KEY (`idArtistas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LaRockola`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LaRockola`.`Genero` (
  `idGenero` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGenero`),
  UNIQUE INDEX `idGenero_UNIQUE` (`idGenero` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LaRockola`.`Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LaRockola`.`Album` (
  `idAlbum` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `anno` DATE NULL,
  `IdArtistaAlbum` INT NOT NULL,
  PRIMARY KEY (`idAlbum`),
  UNIQUE INDEX `idAlbum_UNIQUE` (`idAlbum` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LaRockola`.`Cancion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LaRockola`.`Cancion` (
  `idCanciones` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `letra` LONGTEXT NULL,
  `idioma` VARCHAR(4) NULL,
  `idGenero` INT NOT NULL,
  `idalbum` INT NOT NULL,
  PRIMARY KEY (`idCanciones`),
  UNIQUE INDEX `idCanciones_UNIQUE` (`idCanciones` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LaRockola`.`ListaReproduccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LaRockola`.`ListaReproduccion` (
  `idListaReproduccion` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `fechaUltimaReproduccion` DATE NULL,
  `listaFavorita` VARCHAR(1) NULL,
  PRIMARY KEY (`idListaReproduccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LaRockola`.`ListaCancion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LaRockola`.`ListaCancion` (
  `idListaCancion` INT NOT NULL AUTO_INCREMENT,
  `idCancion` INT NOT NULL,
  `idLista` INT NOT NULL,
  PRIMARY KEY (`idListaCancion`),
  UNIQUE INDEX `idListaCancion_UNIQUE` (`idListaCancion` ASC) VISIBLE,
  INDEX `ListaCancion_idx` (`idCancion` ASC) VISIBLE,
  INDEX `cancionLista_idx` (`idLista` ASC) VISIBLE,
  CONSTRAINT `ListaCancion`
    FOREIGN KEY (`idCancion`)
    REFERENCES `LaRockola`.`Cancion` (`idCanciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cancionLista`
    FOREIGN KEY (`idLista`)
    REFERENCES `LaRockola`.`ListaReproduccion` (`idListaReproduccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
